[[pages]]
name = "Main Menu"
icon = "📌"
is_section = true

[[pages]]
path = "pages/menu.py"
name = "Home"
icon = "🏠"

[[pages]]
path = "pages/medication.py"
name = "Medication"
icon = "💊"

[[pages]]
path = "pages/routine.py"
name = "Routine"
icon = "🗓️"

[[pages]]
path = "pages/events.py"
name = "Events"
icon = "📆"

[[pages]]
name = "Others"
icon = "🔧"
is_section = true

[[pages]]
path = "pages/settings.py"
name = "Settings"
icon = "⚙️"

[[pages]]
path = "pages/admin.py"
name = "Admin"
icon = "🛠️"